kind: LocalConfig
apiversion: odo.dev/v1alpha1
ComponentSettings:
  Type: python
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  Application: app
  Project: test
  Name: python-daac-broker-sqtu
